### ISSUE TITLE
Convert report to LaTeX

### ISSUE THREAD

**Issue by katyhuff** [arfc/2021-fountain-review#1]
Put your content into the tex files
- [x] clone this repo
- [x] open title.tex in your favorite txt editor and edit the title, authors, etc. 
- [x] uncomment \input{main}
- [x] save and close
- [x] open main.tex 
- [x] edit main.tex with the content (text, sections,etc). 

Note, here's a latex section: 
```tex
\section{Introduction}
Here's the intro text.
```

**Comment by katyhuff** [comment]
One option, to get started on the syntax for your main.tex file, is to use pandoc. This will require the following steps:

- [ ] download your google doc as .doc, .docx, or .rtf
- [ ] open the command line and find that file (let's say it's googledoc.docx)
- [ ]  Make sure you have pandoc installed with `which pandoc` on the command line
- [ ] Try something like `pandoc -s googledoc.docx -o main.tex`
- [ ] open it up, see what it looks like, and see if you can copy/paste some of it into the main.tex in the repo

**Comment by npanczyk** [comment]
Converted review to latex report format and made rough table out of original google sheets data-- this will probably need to be edited. Also, will need help with citations. Will open new issue to start review process.
